//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdonRabbit.Analyzer {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UdonRabbit.Analyzer.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Use the regular static method call instead of using static directive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0030CodeFixTitle {
            get {
                return ResourceManager.GetString("URA0030CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use the qualified type name instead of namespace alias に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0031CodeFixTitle {
            get {
                return ResourceManager.GetString("URA0031CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove UdonSyncType.Linear option from UdonSynced attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0034CodeFixTitle {
            get {
                return ResourceManager.GetString("URA0034CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make the method as public に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0041CodeFixTitie {
            get {
                return ResourceManager.GetString("URA0041CodeFixTitie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make the method as public に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0042CodeFixTitle {
            get {
                return ResourceManager.GetString("URA0042CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make the method callable over the network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0043CodeFixTitle {
            get {
                return ResourceManager.GetString("URA0043CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create an empty method named &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0045CodeFixTitle {
            get {
                return ResourceManager.GetString("URA0045CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove UdonSyncType.Smooth option from UdonSynced attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0046CodeFixTitle {
            get {
                return ResourceManager.GetString("URA0046CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generic method of GetComponent&lt;T&gt; is currently broken in Udon, use the GetComponent(Type) instead of GetComponent&lt;T&gt;() に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0047CodeFixTitle {
            get {
                return ResourceManager.GetString("URA0047CodeFixTitle", resourceCulture);
            }
        }
    }
}
