//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdonRabbit.Analyzer {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UdonRabbit.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Type names should be all uppercase. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type name &apos;{0}&apos; contains lowercase letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type name contains lowercase letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Should not use method that does not exposed to Udon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0001Description {
            get {
                return ResourceManager.GetString("URA0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method &apos;{0}&apos; is not exposed to Udon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0001MessageFormat {
            get {
                return ResourceManager.GetString("URA0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method is not exposed to Udon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0001Title {
            get {
                return ResourceManager.GetString("URA0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Should not use field accessor that does not exposed to Udon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0002Description {
            get {
                return ResourceManager.GetString("URA0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field Accessor &apos;{0}&apos; is not exposed to Udon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0002MessageFormat {
            get {
                return ResourceManager.GetString("URA0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field Accessor is not exposed to Udon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0002Title {
            get {
                return ResourceManager.GetString("URA0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp only supports 1 type generic methods at the moment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0003Description {
            get {
                return ResourceManager.GetString("URA0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp only supports 1 type generic methods, but you use {0} type generic method. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0003MessageFormat {
            get {
                return ResourceManager.GetString("URA0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# only supports one type generics. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0003Title {
            get {
                return ResourceManager.GetString("URA0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently supports static method declarations. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0004Description {
            get {
                return ResourceManager.GetString("URA0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently supports static method declarations. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0004MessageFormat {
            get {
                return ResourceManager.GetString("URA0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not currently supports static method declaration. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0004Title {
            get {
                return ResourceManager.GetString("URA0004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support inheriting from interfaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0005Description {
            get {
                return ResourceManager.GetString("URA0005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support inheriting from interfaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0005MessageFormat {
            get {
                return ResourceManager.GetString("URA0005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not yet support inheriting from interfaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0005Title {
            get {
                return ResourceManager.GetString("URA0005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently support constructors on UdonSharpBehaviours, use the Start() に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0007Description {
            get {
                return ResourceManager.GetString("URA0007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently support constructors on UdonSharpBehaviours, use the Start() に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0007MessageFormat {
            get {
                return ResourceManager.GetString("URA0007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not currently support constructors on UdonSharpBehaviour に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0007Title {
            get {
                return ResourceManager.GetString("URA0007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User property declarations are not yet supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0008Description {
            get {
                return ResourceManager.GetString("URA0008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User property declarations are not yet supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0008MessageFormat {
            get {
                return ResourceManager.GetString("URA0008MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User property declarations are not yet supported by U# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0008Title {
            get {
                return ResourceManager.GetString("URA0008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base type calling is not yet supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0009Description {
            get {
                return ResourceManager.GetString("URA0009Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base type calling is not yet supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0009MessageFormat {
            get {
                return ResourceManager.GetString("URA0009MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base type calling is not yet supported by U# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0009Title {
            get {
                return ResourceManager.GetString("URA0009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default expressions are not yet supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0010Description {
            get {
                return ResourceManager.GetString("URA0010Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default expressions are not yet supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0010MessageFormat {
            get {
                return ResourceManager.GetString("URA0010MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default expressions are not yet supported by U# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0010Title {
            get {
                return ResourceManager.GetString("URA0010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try/Catch/Finally is not supported by UdonSharp since Udon does not have a way to handle exceptions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0011Description {
            get {
                return ResourceManager.GetString("URA0011Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try/Catch/Finally is not supported by UdonSharp since Udon does not have a way to handle exceptions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0011MessageFormat {
            get {
                return ResourceManager.GetString("URA0011MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try/Catch/Finally is not supported by U# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0011Title {
            get {
                return ResourceManager.GetString("URA0011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not support throwing exceptions since Udon does not have support for exception throwing at the moment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0012Description {
            get {
                return ResourceManager.GetString("URA0012Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not support throwing exceptions since Udon does not have support for exception throwing at the moment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0012MessageFormat {
            get {
                return ResourceManager.GetString("URA0012MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not support throwing exceptions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0012Title {
            get {
                return ResourceManager.GetString("URA0012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not support multidimensional arrays at the moment, use jagged arrays instead for now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0013Description {
            get {
                return ResourceManager.GetString("URA0013Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not support multidimensional arrays at the moment, use jagged arrays instead for now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0013MessageFormat {
            get {
                return ResourceManager.GetString("URA0013MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not support multidimensional arrays, use jagged arrays に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0013Title {
            get {
                return ResourceManager.GetString("URA0013Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not support multidimensional array accesses yet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0014Description {
            get {
                return ResourceManager.GetString("URA0014Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not support multidimensional array accesses yet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0014MessageFormat {
            get {
                return ResourceManager.GetString("URA0014MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not support multidimensional array accesses yet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0014Title {
            get {
                return ResourceManager.GetString("URA0014Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently support null conditional operators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0015Description {
            get {
                return ResourceManager.GetString("URA0015Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently support null conditional operators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0015MessageFormat {
            get {
                return ResourceManager.GetString("URA0015MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not currently support null conditional operators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0015Title {
            get {
                return ResourceManager.GetString("URA0015Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support the &apos;Awake&apos; event, use &apos;Start&apos; instead に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0016Description {
            get {
                return ResourceManager.GetString("URA0016Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support the &apos;Awake&apos; event, use &apos;Start&apos; instead に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0016MessageFormat {
            get {
                return ResourceManager.GetString("URA0016MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support the &apos;Awake&apos; event, use &apos;Start&apos; instead に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0016Title {
            get {
                return ResourceManager.GetString("URA0016Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support &apos;out&apos; parameters on user-defined methods に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0017Description {
            get {
                return ResourceManager.GetString("URA0017Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support &apos;out&apos; parameters on user-defined methods に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0017MessageFormat {
            get {
                return ResourceManager.GetString("URA0017MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not yet support &apos;out&apos; parameters on user-defined methods に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0017Title {
            get {
                return ResourceManager.GetString("URA0017Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support &apos;in&apos; parameters on user-defined methods に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0018Description {
            get {
                return ResourceManager.GetString("URA0018Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support &apos;in&apos; parameters on user-defined methods に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0018MessageFormat {
            get {
                return ResourceManager.GetString("URA0018MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not yet support &apos;in&apos; parameters on user-defined methods に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0018Title {
            get {
                return ResourceManager.GetString("URA0018Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support &apos;ref&apos; parameters on user-defined methods に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0019Description {
            get {
                return ResourceManager.GetString("URA0019Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support &apos;ref&apos; parameters on user-defined methods に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0019MessageFormat {
            get {
                return ResourceManager.GetString("URA0019MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not yet support &apos;ref&apos; parameters on user-defined methods に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0019Title {
            get {
                return ResourceManager.GetString("URA0019Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;is&apos; keyword is not yet supported by UdonSharp since Udon does not expose what is necessary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0020Description {
            get {
                return ResourceManager.GetString("URA0020Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;is&apos; keyword is not yet supported by UdonSharp since Udon does not expose what is necessary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0020MessageFormat {
            get {
                return ResourceManager.GetString("URA0020MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;is&apos; keyword is not yet supported by U# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0020Title {
            get {
                return ResourceManager.GetString("URA0020Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;as&apos; keyword is not yet supported by UdonSharp since Udon does not expose what is necessary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0021Description {
            get {
                return ResourceManager.GetString("URA0021Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;as&apos; keyword is not yet supported by UdonSharp since Udon does not expose what is necessary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0021MessageFormat {
            get {
                return ResourceManager.GetString("URA0021MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &apos;as&apos; keyword is not yet supported by U# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0021Title {
            get {
                return ResourceManager.GetString("URA0021Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently support type checking with the &apos;is&apos; keyword since Udon does not yet expose the proper functionality for type checking. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0022Description {
            get {
                return ResourceManager.GetString("URA0022Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently support type checking with the &apos;is&apos; keyword since Udon does not yet expose the proper functionality for type checking. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0022MessageFormat {
            get {
                return ResourceManager.GetString("URA0022MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not currently support type checking with the &apos;is&apos; keyword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0022Title {
            get {
                return ResourceManager.GetString("URA0022Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only one class declaration per file is currently supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0023Description {
            get {
                return ResourceManager.GetString("URA0023Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only one class declaration per file is currently supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0023MessageFormat {
            get {
                return ResourceManager.GetString("URA0023MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only one class declaration per file is currently supported by U# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0023Title {
            get {
                return ResourceManager.GetString("URA0023Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp custom methods currently do not support default arguments or params arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0024Description {
            get {
                return ResourceManager.GetString("URA0024Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp custom methods currently do not support default arguments or params arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0024MessageFormat {
            get {
                return ResourceManager.GetString("URA0024MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# custom methods currently do not support default arguments or params arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0024Title {
            get {
                return ResourceManager.GetString("URA0024Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static fields are not yet supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0025Description {
            get {
                return ResourceManager.GetString("URA0025Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static fields are not yet supported by UdonSharp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0025MessageFormat {
            get {
                return ResourceManager.GetString("URA0025MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static fields are not yet supported by U# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0025Title {
            get {
                return ResourceManager.GetString("URA0025Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support return values of this type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0026Description {
            get {
                return ResourceManager.GetString("URA0026Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support return values of type &apos;{0}&apos; yet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0026MessageFormat {
            get {
                return ResourceManager.GetString("URA0026MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support return values of this type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0026Title {
            get {
                return ResourceManager.GetString("URA0026Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support method parameters of this type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0027Description {
            get {
                return ResourceManager.GetString("URA0027Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support method parameters of type &apos;{0}&apos; yet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0027MessageFormat {
            get {
                return ResourceManager.GetString("URA0027MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support method parameters of this type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0027Title {
            get {
                return ResourceManager.GetString("URA0027Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently support using typeof on user defined types に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0029Description {
            get {
                return ResourceManager.GetString("URA0029Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not currently support using typeof on user defined types に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0029MessageFormat {
            get {
                return ResourceManager.GetString("URA0029MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not currently support using typeof on user defined types に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0029Title {
            get {
                return ResourceManager.GetString("URA0029Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support static using directives に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0030Description {
            get {
                return ResourceManager.GetString("URA0030Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support static using directives に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0030MessageFormat {
            get {
                return ResourceManager.GetString("URA0030MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not yet support static using directives に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0030Title {
            get {
                return ResourceManager.GetString("URA0030Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support namespace alias directives に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0031Description {
            get {
                return ResourceManager.GetString("URA0031Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UdonSharp does not yet support namespace alias directives に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0031MessageFormat {
            get {
                return ResourceManager.GetString("URA0031MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U# does not yet support namespace alias directives に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0031Title {
            get {
                return ResourceManager.GetString("URA0031Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support variables of this type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0032Description {
            get {
                return ResourceManager.GetString("URA0032Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support variables of type &apos;{0}&apos; yet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0032MessageFormat {
            get {
                return ResourceManager.GetString("URA0032MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support variables of this type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0032Title {
            get {
                return ResourceManager.GetString("URA0032Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not currently support syncing of the this type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0033Description {
            get {
                return ResourceManager.GetString("URA0033Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not currently support syncing of the type &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0033MessageFormat {
            get {
                return ResourceManager.GetString("URA0033MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not currently support syncing of the this type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0033Title {
            get {
                return ResourceManager.GetString("URA0033Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support linear interpolation of the synced type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0034Description {
            get {
                return ResourceManager.GetString("URA0034Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support linear interpolation of the synced type &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0034MessageFormat {
            get {
                return ResourceManager.GetString("URA0034MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support linear interpolation of the synced type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0034Title {
            get {
                return ResourceManager.GetString("URA0034Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support variable tweening when the behaviour is in Manual sync mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0035Description {
            get {
                return ResourceManager.GetString("URA0035Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support variable tweening when the behaviour is in Manual sync mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0035MessageFormat {
            get {
                return ResourceManager.GetString("URA0035MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Udon does not support variable tweening when the behaviour is in Manual sync mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URA0035Title {
            get {
                return ResourceManager.GetString("URA0035Title", resourceCulture);
            }
        }
    }
}
